"""add credit redemption and loyalty earn to sales

Revision ID: 057a0ce31dc8
Revises: 317003552c34
Create Date: 2026-08-05 05:08:14.425033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057a0ce31dc8'
down_revision: Union[str, None] = '317003552c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sales',
        sa.Column('credit_applied', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'sales',
        sa.Column('loyalty_points_earned', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'loyalty_points_earned')
    op.drop_column('sales', 'credit_applied')
    # ### end Alembic commands ###
