"""business profile fields for printed documents

Revision ID: 2d8bb0063f2d
Revises: 6954b1135785
Create Date: 2026-08-04 22:22:34.582899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8bb0063f2d'
down_revision: Union[str, None] = '6954b1135785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('business_name', sa.String(length=200), nullable=True))
    op.add_column('app_settings', sa.Column('business_address', sa.String(length=500), nullable=True))
    op.add_column('app_settings', sa.Column('business_gstin', sa.String(length=20), nullable=True))
    op.add_column('app_settings', sa.Column('business_phone', sa.String(length=20), nullable=True))
    op.add_column('app_settings', sa.Column('business_email', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('invoice_footer_text', sa.String(length=500), nullable=True))
    op.add_column(
        'app_settings',
        sa.Column('show_hsn_on_documents', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('app_settings', 'show_hsn_on_documents', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'show_hsn_on_documents')
    op.drop_column('app_settings', 'invoice_footer_text')
    op.drop_column('app_settings', 'business_email')
    op.drop_column('app_settings', 'business_phone')
    op.drop_column('app_settings', 'business_gstin')
    op.drop_column('app_settings', 'business_address')
    op.drop_column('app_settings', 'business_name')
    # ### end Alembic commands ###
