"""phase 3 subscription plans feature flags

Revision ID: 31a11fe886ba
Revises: eacd4d950ed2
Create Date: 2026-08-07 00:59:05.772336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31a11fe886ba'
down_revision: Union[str, None] = 'eacd4d950ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.ENUM('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptionplanname', create_type=False), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_outlets', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    # ### end Alembic commands ###

    # --- Seed the 4 plans, every module enabled on every plan (see
    # app.services.feature_flags - no gating is wired in yet). ---
    from app.services.feature_flags import FEATURE_CATALOG

    all_enabled = {code: True for code in FEATURE_CATALOG}
    subscription_plans_t = sa.table(
        "subscription_plans",
        sa.column("name", sa.String), sa.column("display_name", sa.String),
        sa.column("max_users", sa.Integer), sa.column("max_outlets", sa.Integer),
        sa.column("features", postgresql.JSONB),
    )
    op.bulk_insert(subscription_plans_t, [
        {"name": "FREE", "display_name": "Free", "max_users": 3, "max_outlets": 1, "features": all_enabled},
        {"name": "STARTER", "display_name": "Starter", "max_users": 10, "max_outlets": 3, "features": all_enabled},
        {"name": "PROFESSIONAL", "display_name": "Professional", "max_users": 50, "max_outlets": 10, "features": all_enabled},
        {"name": "ENTERPRISE", "display_name": "Enterprise", "max_users": None, "max_outlets": None, "features": all_enabled},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
