"""add discount rules and coupon fields

Revision ID: 345e7974ec33
Revises: a5c94b46c2a1
Create Date: 2026-08-05 16:06:27.524326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e7974ec33'
down_revision: Union[str, None] = 'a5c94b46c2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', 'BOGO', name='discounttype'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'CATEGORY', 'BRAND', 'PRODUCT', name='discountscope'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('vip_only', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buy_quantity', sa.Integer(), nullable=True),
    sa.Column('get_quantity', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_code'), 'discount_rules', ['code'], unique=True)
    op.add_column('sales', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column('sales', sa.Column('discount_rule_id', sa.Integer(), nullable=True))
    op.add_column(
        'sales',
        sa.Column('rule_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.create_foreign_key(None, 'sales', 'discount_rules', ['discount_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'rule_discount_amount')
    op.drop_column('sales', 'discount_rule_id')
    op.drop_column('sales', 'coupon_code')
    op.drop_index(op.f('ix_discount_rules_code'), table_name='discount_rules')
    op.drop_table('discount_rules')
    # ### end Alembic commands ###
    sa.Enum(name='discounttype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='discountscope').drop(op.get_bind(), checkfirst=True)
