"""add app_settings.logo_url

Revision ID: 3ad23531e38c
Revises: 3b43b4f73ca1
Create Date: 2026-08-06 02:48:27.286289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad23531e38c'
down_revision: Union[str, None] = '3b43b4f73ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'logo_url')
    # ### end Alembic commands ###
