"""add campaign offer_code and product_name placeholder fields

Revision ID: 3b43b4f73ca1
Revises: 75e9bd48ee6d
Create Date: 2026-08-05 23:46:52.091113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b43b4f73ca1'
down_revision: Union[str, None] = '75e9bd48ee6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('offer_code', sa.String(length=40), nullable=True))
    op.add_column('campaigns', sa.Column('product_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'product_name')
    op.drop_column('campaigns', 'offer_code')
    # ### end Alembic commands ###
