"""add whatsapp campaigns

Revision ID: 4b2abff60e33
Revises: 345e7974ec33
Create Date: 2026-08-05 16:25:14.882165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4b2abff60e33'
down_revision: Union[str, None] = '345e7974ec33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('segment_type', sa.Enum('ALL', 'VIP', 'TAG', 'CATEGORY_PURCHASE', 'BRAND_PURCHASE', 'INACTIVE', 'BIRTHDAY_MONTH', name='segmenttype'), nullable=False),
    sa.Column('segment_tag', sa.String(length=60), nullable=True),
    sa.Column('segment_category_id', sa.Integer(), nullable=True),
    sa.Column('segment_brand', sa.String(length=120), nullable=True),
    sa.Column('segment_days', sa.Integer(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['segment_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column(
        'status',
        postgresql.ENUM('LINK_GENERATED', 'SENT', 'FAILED', name='whatsappmessagestatus', create_type=False),
        nullable=False,
    ),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_recipients')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
    sa.Enum(name='segmenttype').drop(op.get_bind(), checkfirst=True)
