"""add hardware_ai_settings

Revision ID: 5cdbf2bcd475
Revises: 3ad23531e38c
Create Date: 2026-08-06 02:55:41.438190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdbf2bcd475'
down_revision: Union[str, None] = '3ad23531e38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_min_length', sa.Integer(), nullable=True),
    sa.Column('barcode_beep_on_scan', sa.Boolean(), nullable=False),
    sa.Column('thermal_printer_name', sa.String(length=150), nullable=True),
    sa.Column('thermal_printer_ip', sa.String(length=50), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('biometric_device_api_url', sa.String(length=300), nullable=True),
    sa.Column('biometric_api_key', sa.String(length=500), nullable=True),
    sa.Column('openai_api_key', sa.String(length=500), nullable=True),
    sa.Column('openai_model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hardware_ai_settings')
    # ### end Alembic commands ###
