"""printing settings, app settings, sale customer email

Revision ID: 6954b1135785
Revises: f8aa40c47f8a
Create Date: 2026-08-04 21:46:31.014763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6954b1135785'
down_revision: Union[str, None] = 'f8aa40c47f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_cloud_api_token', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_api_version', sa.String(length=10), nullable=True),
    sa.Column('sms_provider', sa.Enum('NONE', 'TWILIO', 'GENERIC_WEBHOOK', name='smsprovider'), nullable=False),
    sa.Column('sms_account_sid', sa.String(length=120), nullable=True),
    sa.Column('sms_auth_token', sa.String(length=500), nullable=True),
    sa.Column('sms_from_number', sa.String(length=20), nullable=True),
    sa.Column('sms_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('sms_webhook_auth_header', sa.String(length=500), nullable=True),
    sa.Column('email_smtp_host', sa.String(length=255), nullable=True),
    sa.Column('email_smtp_port', sa.Integer(), nullable=False),
    sa.Column('email_smtp_username', sa.String(length=255), nullable=True),
    sa.Column('email_smtp_password', sa.String(length=500), nullable=True),
    sa.Column('email_from_address', sa.String(length=255), nullable=True),
    sa.Column('email_use_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    papersize_enum = sa.Enum('A4', 'THERMAL_58', 'THERMAL_80', name='papersize')
    papersize_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('outlets', sa.Column('receipt_paper_size', papersize_enum, nullable=False, server_default='A4'))
    op.add_column('outlets', sa.Column('transfer_paper_size', papersize_enum, nullable=False, server_default='A4'))
    op.alter_column('outlets', 'receipt_paper_size', server_default=None)
    op.alter_column('outlets', 'transfer_paper_size', server_default=None)
    op.add_column('sales', sa.Column('customer_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'customer_email')
    op.drop_column('outlets', 'transfer_paper_size')
    op.drop_column('outlets', 'receipt_paper_size')
    op.drop_table('app_settings')
    sa.Enum(name='papersize').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
