"""campaign media, buttons, scheduling, message templates, whatsapp status expansion

Revision ID: 75e9bd48ee6d
Revises: 96d60df15c63
Create Date: 2026-08-05 23:44:00.595546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75e9bd48ee6d'
down_revision: Union[str, None] = '96d60df15c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='campaignmediatype').create(op.get_bind(), checkfirst=True)
    sa.Enum('SCHEDULED', 'SENT', 'FAILED', name='campaignstatus').create(op.get_bind(), checkfirst=True)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign_recipients', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_recipients', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column(
        'campaigns',
        sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='campaignmediatype', create_type=False), nullable=True),
    )
    op.add_column('campaigns', sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'campaigns',
        sa.Column(
            'status',
            sa.Enum('SCHEDULED', 'SENT', 'FAILED', name='campaignstatus', create_type=False),
            nullable=False,
            server_default='SENT',
        ),
    )
    op.alter_column('campaigns', 'status', server_default=None)
    op.execute("ALTER TYPE whatsappmessagestatus ADD VALUE IF NOT EXISTS 'delivered'")
    op.execute("ALTER TYPE whatsappmessagestatus ADD VALUE IF NOT EXISTS 'read'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres can't drop enum values without recreating the type; 'delivered'/'read'
    # are left in place on downgrade (harmless - just unused values).
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'scheduled_at')
    op.drop_column('campaigns', 'buttons')
    op.drop_column('campaigns', 'media_type')
    op.drop_column('campaigns', 'media_url')
    op.drop_column('campaign_recipients', 'read_at')
    op.drop_column('campaign_recipients', 'delivered_at')
    op.drop_table('message_templates')
    sa.Enum(name='campaignstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='campaignmediatype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
