"""add email/sms provider integrations, drop legacy AppSettings sms/email fields

Revision ID: 96d60df15c63
Revises: c2b75840bec6
Create Date: 2026-08-05 23:11:19.588265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d60df15c63'
down_revision: Union[str, None] = 'c2b75840bec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('BREVO', 'RESEND', 'EMAILJS', 'SMTP_GENERIC', 'GMAIL_SMTP', 'OUTLOOK_SMTP', name='emailprovidertype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('secret_key', sa.String(length=500), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=500), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_providers_provider'), 'email_providers', ['provider'], unique=True)
    op.create_table('sms_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('MSG91', 'TEXTLOCAL_INDIA', 'TWO_FACTOR', 'GENERIC_HTTP', 'TWILIO', name='smsprovidertype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('auth_token', sa.String(length=500), nullable=True),
    sa.Column('sender_id', sa.String(length=40), nullable=True),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_provider_configs_provider'), 'sms_provider_configs', ['provider'], unique=True)
    op.drop_column('app_settings', 'email_smtp_host')
    op.drop_column('app_settings', 'sms_provider')
    op.drop_column('app_settings', 'sms_webhook_auth_header')
    op.drop_column('app_settings', 'email_smtp_username')
    op.drop_column('app_settings', 'sms_webhook_url')
    op.drop_column('app_settings', 'sms_auth_token')
    op.drop_column('app_settings', 'email_from_address')
    op.drop_column('app_settings', 'email_use_tls')
    op.drop_column('app_settings', 'email_smtp_port')
    op.drop_column('app_settings', 'email_smtp_password')
    op.drop_column('app_settings', 'sms_account_sid')
    op.drop_column('app_settings', 'sms_from_number')
    sa.Enum(name='smsprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('sms_from_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('sms_account_sid', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('email_smtp_password', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('email_smtp_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('email_use_tls', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('email_from_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('sms_auth_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('sms_webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('email_smtp_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('sms_webhook_auth_header', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('sms_provider', postgresql.ENUM('NONE', 'TWILIO', 'GENERIC_WEBHOOK', name='smsprovider'), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('email_smtp_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sms_provider_configs_provider'), table_name='sms_provider_configs')
    op.drop_table('sms_provider_configs')
    op.drop_index(op.f('ix_email_providers_provider'), table_name='email_providers')
    op.drop_table('email_providers')
    # ### end Alembic commands ###
